name: Import miEPG original

on:
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout target repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}

      - name: Clone original repository
        run: |
          git clone --depth=1 https://github.com/davidmuma/miEPG.git source
          rm -rf source/.git

      - name: Replace repository contents safely
        run: |
          mkdir newcontent
          rsync -a source/ newcontent/ --ignore-errors --force || true

          find . -mindepth 1 -maxdepth 1 ! -name ".git" ! -name "newcontent" -exec rm -rf {} +

          rsync -a newcontent/ . --ignore-errors --force || true

      - name: Set remote with PAT
        run: |
          git remote set-url origin https://roisiano:${{ secrets.PAT }}@github.com/roisiano/miEPG-v3.6.git

      - name: Commit and push changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add .
          git commit -m "Sync from davidmuma/miEPG" || echo "No changes to commit"
          git push


