name: Import miEPG original

on:
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout empty repo
        uses: actions/checkout@v4

      - name: Clone original repository
        run: |
          git clone --depth=1 https://github.com/davidmuma/miEPG.git source

      - name: Copy files
        run: |
          cp -R source/* .
          cp -R source/.[!.]* . || true

      - name: Commit and push changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add .
          git commit -m "Import from davidmuma/miEPG" || echo "No changes to commit"
          git push
