name: miEPG

on:
  schedule:
    - cron: '30 11 * * * ' # Ejecutar a las 13:30 AM
  workflow_dispatch:

permissions:
   contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del repositorio
      uses: actions/checkout@v2

    - name: Comprobar si xmllint está instalado
      run: |
        if ! command -v xmllint &> /dev/null
        then
          echo "xmllint no está instalado. Instalando..."
          sudo apt-get update
          sudo apt-get install -y libxml2-utils
        else
          echo "xmllint ya está instalado"
        fi

    - name: Dar permisos de ejecución al script
      run: chmod +x .github/workflows/EPG_script.sh

    - name: Ejecutar script
      run: .github/workflows/EPG_script.sh

    - name: Configurar identidad de Git
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"

    - name: Subir archivos 
      run: |
        git add miEPG.xml miEPG.xml.gz
        git commit -m "Actualización de miEPG.xml y miEPG.xml.gz"
        git push --force
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

