name: Generar EPG

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Instalar dependencias
        run: |
          sudo apt-get update
          sudo apt-get install -y xmlstarlet wget gzip

      - name: Ejecutar script EPG
        run: |
          chmod +x .github/workflows/EPG_script.sh
          .github/workflows/EPG_script.sh

      - name: Subir resultados
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Actualización automática de EPG"
          file_pattern: |
            miEPG.xml.gz
            epg_acumulado.xml.gz


